### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jsolvason** [brentp/cruzdb#22]
It may just be me, but after installing cruzdb...

`pip install cruzdb`

... and trying to import it in python and python3 I am getting this error:

```
>>> import cruzdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/josephsolvason/miniconda3/lib/python3.6/site-packages/cruzdb/__init__.py", line 5, in <module>
    from . import soup
  File "/Users/josephsolvason/miniconda3/lib/python3.6/site-packages/cruzdb/soup.py", line 1, in <module>
    from . import sqlsoup
  File "/Users/josephsolvason/miniconda3/lib/python3.6/site-packages/cruzdb/sqlsoup.py", line 458
    except KeyError, ke:
                   ^
SyntaxError: invalid syntax
>>> 

```

Thoughts?

Joe

**Comment by ipstone** [comment]
I have the same error after installing cruzdb from pip

**Comment by adelq** [comment]
You are probably using Python 3, since that exception syntax is no longer allowed. Try again with Python 2.

**Comment by Biojenifer** [comment]
Do you know if it is possible now to install it using Python 3?

**Comment by brentp** [comment]
python 3 installation works for me. But if you have issues, you can report them here.

**Comment by bayesfactor** [comment]
I had the same error with python 3.6.9

**Comment by beibeixiaomu** [comment]
@brentp 

Hello!

When I use python 3.9.2.   I had the same error as above.

And when I use python 2.7.15.   Errors are as following:
Traceback (most recent call last):
  File "/home/data/gma15/miniconda3/envs/combineP/bin/comb-p", line 39, in <module>
    main()
  File "/home/data/gma15/miniconda3/envs/combineP/bin/comb-p", line 36, in main
    module.main()
  File "/home/data/gma15/miniconda3/envs/combineP/lib/python2.7/site-packages/cpv/pipeline.py", line 9, in main
    from ._common import get_col_num
  File "/home/data/gma15/miniconda3/envs/combineP/lib/python2.7/site-packages/cpv/_common.py", line 164, in <module>
    IMapIterator.next = wrapper(IMapIterator.next)
  File "/home/data/gma15/miniconda3/envs/combineP/lib/python2.7/site-packages/cpv/_common.py", line 161, in wrapper
    def wrap(self, timeout=threading.TIMEOUT_MAX):
AttributeError: 'module' object has no attribute 'TIMEOUT_MAX'

I wonder which version of python should be used and if you can give me a list of all requirements.
Thank you very much for your contribution.
I am looking forward to your help.
Sincerely
Judy
