### ISSUE TITLE
invalid syntax?

### ISSUE THREAD

**Issue by radwaraed** [brentp/cruzdb#27]
Hello,
I just installed the cruzdb package and came across this error as soon as I tried to import the sequences (from cruzdb import sequence)

`
 File "/Users/Radwa/anaconda/lib/python3.6/site-packages/cruzdb/sqlsoup.py", line 458
    except KeyError, ke:
                   ^
SyntaxError: invalid syntax`

**Comment by brentp** [comment]
I haven't worked on cruzdb for some time. It's likely that there are many parts of it that do not support python3. I'd accept a pull request to fix that.

**Comment by radwaraed** [comment]
Many thanks Brent for your reply. I am new to this, so I didn't realize there was a pull request.

**Comment by sammosummo** [comment]
It seems this issue was never fixed, I experienced it today (2021-09-14).

**Comment by marcmaxson** [comment]
Still a problem today (2021-10-07)

```
`Python 3.8.11 (default, Aug  6 2021, 08:56:27) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cruzdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/qc38/lib/python3.8/site-packages/cruzdb/__init__.py", line 5, in <module>
    from . import soup
  File "/opt/anaconda3/envs/qc38/lib/python3.8/site-packages/cruzdb/soup.py", line 1, in <module>
    from . import sqlsoup
  File "/opt/anaconda3/envs/qc38/lib/python3.8/site-packages/cruzdb/sqlsoup.py", line 458
    except KeyError, ke:
                   ^
SyntaxError: invalid syntax`
```

In python 3, the proper except is:

```
try:
    .....
except Exception as e:
    raise Exception(e)
```

the comma is no longer supported.

**Comment by brentp** [comment]
happy to accept a PR that fixes python3 compat.

**Comment by marcmaxson** [comment]
Thanks. I can't work on it immediately, but I will send in a PR if I get a
chance to update it.
